site_name: Documentation Outils

theme:
  name: material
  font: false
  language: 'fr'
  feature:
    tabs: true
  palette:
    scheme: default
    primary: 'blue grey'
    accent: 'orange'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - 'mathjax/MathJax.min.js'

plugins:
  - search
  - bibtex:
      bib_dir: 'bib'
      cite_style: "pandoc"
  - img2fig
  - awesome-pages:
      collapse_single_pages: false
  - minify:
      minify_html: true

use_directory_urls: false
nav:
  - Accueil: index.md
  - Git: 
    - 'git': './git/git.md'
  - Mkdocs:
    - 'installation sous Windows': './mkdocs/mkdocs-windows-installation.md'
    - '[obsolète] liens symboliques sous Windows': './mkdocs/mkdocs-liens-symboliques.md'
  - Markdown:
    - 'syntaxe': './markdown/markdown-syntaxe.md'
  - Pandoc:
    - 'installation sous Windows': './pandoc/pandoc-windows-installation.md'
    - 'lancement du script _build.sh_': './pandoc/pandoc-windows-script-build.md'
